markers:
  12:
    pose: [2.0390443801879883,  1.3573353290557861,  3.141592653589793]
    side: front
  10:
    pose: [1.2743217945098877,   5.697437286376953, -1.5707963267948966]
    side: left
  2:
    pose: [-1.5813097953796387,  0.13663572072982788, 1.5707963267948966]
    side: right
  13:
    pose: [-0.9238075017929077,  0.07789325714111328, 1.5707963267948966]
    side: right
  11:
    pose: [-1.1963449716567993,   5.725948333740234, -1.5707963267948966]
    side: left